platform :ios, '7.0'
pod 'SSZipArchive',       '~> 0.3.1'
pod 'ColorPopover',  '~> 0.0.1'
pod 'ELCImagePickerController', :git => 'https://github.com/AndyQ/ELCImagePickerController'
pod 'PopoverView',  :git => 'https://github.com/AndyQ/PopoverView'
pod 'InAppSettingsKit', :git => 'https://github.com/AndyQ/InAppSettingsKit'
